/**
 * BookmarkResponse automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {BookmarkResponseMessage} from "./BookmarkResponseMessage";
export interface BookmarkResponse {
    data?: BookmarkResponseMessage
}
