/**
 * BookmarkResponse automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {Bookmark} from "./Bookmark";

export interface BookmarkResponse {
    data?: Bookmark
}

