/**
 * BookmarkCreateResponse automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {BookmarkCreateResponseMessage} from "./BookmarkCreateResponseMessage";
export interface BookmarkCreateResponse {
    data?: BookmarkCreateResponseMessage
}
