"""
Client automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

import sdkgen

from tweet_tag import TweetTag

class Client(sdkgen.ClientAbstract):
    def __init__(self, base_url: str, credentials: sdkgen.CredentialsInterface):
        super().__init__(base_url, credentials)
    pass

    def tweet(self) -> TweetTag:
        return TweetTag(
            self.http_client,
            self.parser
        )
    pass



    @staticmethod
    def build(token: str):
        return Client("https://api.twitter.com", sdkgen.HttpBearer(token))
    pass
