/**
 * Errors automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {Error} from "./Error";

export interface Errors {
    errors?: Array<Error>
}

