/**
 * Error automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface Error {
    type?: string
    title?: string
    status?: number
    detail?: string
}

