/**
 * ErrorsException automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {KnownStatusCodeException} from "sdkgen-client"

import {Errors} from "./Errors";

export class ErrorsException extends KnownStatusCodeException {

    public constructor(private payload: Errors) {
        super('The server returned an error');
    }

    public getPayload(): Errors {
        return this.payload;
    }

}
