/**
 * Fields automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface Fields {
    "media.fields"?: string
    "place.fields"?: string
    "poll.fields"?: string
    "tweet.fields"?: string
    "user.fields"?: string
}
