/**
 * HideReplyResponse automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {HideReply} from "./HideReply";
export interface HideReplyResponse {
    data?: HideReply
}
