/**
 * HideReplyResponse automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {HideReplyUpdate} from "./HideReplyUpdate";
export interface HideReplyResponse {
    data?: HideReplyUpdate
}
