/**
 * LikeResponse automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {Like} from "./Like";

export interface LikeResponse {
    data?: Like
}

