/**
 * LikeResponse automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {LikeResponseMessage} from "./LikeResponseMessage";
export interface LikeResponse {
    data?: LikeResponseMessage
}
