/**
 * Pagination automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface Pagination {
    start_time?: string
    end_time?: string
    since_id?: string
    until_id?: string
    max_results?: number
    pagination_token?: string
}

