/**
 * QuoteTag automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import axios, {AxiosRequestConfig} from "axios";
import {TagAbstract} from "sdkgen-client"
import {ClientException, UnknownStatusCodeException} from "sdkgen-client";

import {TweetCollectionResponse} from "./TweetCollectionResponse";

export class QuoteTag extends TagAbstract {
    /**
     * Returns Quote Tweets for a Tweet specified by the requested Tweet ID.
     *
     * @returns {Promise<TweetCollectionResponse>}
     * @throws {ClientException}
     */
    public async getAll(tweetId: string, exclude?: string, expansions?: string, maxResults?: number, paginationToken?: string, mediaFields?: string, placeFields?: string, pollFields?: string, tweetFields?: string, userFields?: string): Promise<TweetCollectionResponse> {
        const url = this.parser.url('/2/tweets/:tweet_id/quote_tweets', {
            'tweet_id': tweetId,
        });

        let params: AxiosRequestConfig = {
            url: url,
            method: 'GET',
            params: this.parser.query({
                'exclude': exclude,
                'expansions': expansions,
                'max_results': maxResults,
                'pagination_token': paginationToken,
                'media.fields': mediaFields,
                'place.fields': placeFields,
                'poll.fields': pollFields,
                'tweet.fields': tweetFields,
                'user.fields': userFields,
            }, [
            ]),
        };

        try {
            const response = await this.httpClient.request<TweetCollectionResponse>(params);
            return response.data;
        } catch (error) {
            if (error instanceof ClientException) {
                throw error;
            } else if (axios.isAxiosError(error) && error.response) {
                switch (error.response.status) {
                    default:
                        throw new UnknownStatusCodeException('The server returned an unknown status code');
                }
            } else {
                throw new ClientException('An unknown error occurred: ' + String(error));
            }
        }
    }


}
