/**
 * QuoteTag automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import axios, {AxiosRequestConfig} from "axios";
import {TagAbstract} from "sdkgen-client"
import {ClientException, UnknownStatusCodeException} from "sdkgen-client";

import {Fields} from "./Fields";
import {TweetCollection} from "./TweetCollection";

export class QuoteTag extends TagAbstract {
    /**
     * Returns Quote Tweets for a Tweet specified by the requested Tweet ID.
     *
     * @returns {Promise<TweetCollection>}
     * @throws {ClientException}
     */
    public async getAll(tweetId: string, exclude?: string, expansions?: string, maxResults?: number, paginationToken?: string, fields?: Fields): Promise<TweetCollection> {
        const url = this.parser.url('/2/tweets/:tweet_id/quote_tweets', {
            'tweet_id': tweetId,
        });

        let params: AxiosRequestConfig = {
            url: url,
            method: 'GET',
            headers: {
            },
            params: this.parser.query({
                'exclude': exclude,
                'expansions': expansions,
                'max_results': maxResults,
                'pagination_token': paginationToken,
                'fields': fields,
            }, [
                'fields',
            ]),
        };

        try {
            const response = await this.httpClient.request<TweetCollection>(params);
            return response.data;
        } catch (error) {
            if (error instanceof ClientException) {
                throw error;
            } else if (axios.isAxiosError(error) && error.response) {
                const statusCode = error.response.status;

                throw new UnknownStatusCodeException('The server returned an unknown status code: ' + statusCode);
            } else {
                throw new ClientException('An unknown error occurred: ' + String(error));
            }
        }
    }


}
