/**
 * RetweetTag automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {TagAbstract, HttpRequest} from "sdkgen-client"
import {ClientException, UnknownStatusCodeException} from "sdkgen-client";

import {Errors} from "./Errors";
import {ErrorsException} from "./ErrorsException";
import {Fields} from "./Fields";
import {TweetCollection} from "./TweetCollection";

export class RetweetTag extends TagAbstract {
    /**
     * Returns the Retweets for a given Tweet ID.
     *
     * @returns {Promise<TweetCollection>}
     * @throws {ErrorsException}
     * @throws {ClientException}
     */
    public async getAll(tweetId: string, expansions?: string, maxResults?: number, fields?: Fields): Promise<TweetCollection> {
        const url = this.parser.url('/2/tweets/:tweet_id/retweets', {
            'tweet_id': tweetId,
        });

        let request: HttpRequest = {
            url: url,
            method: 'GET',
            headers: {
            },
            params: this.parser.query({
                'expansions': expansions,
                'max_results': maxResults,
                'fields': fields,
            }, [
                'fields',
            ]),
        };

        const response = await this.httpClient.request(request);
        if (response.ok) {
            return await response.json() as TweetCollection;
        }

        const statusCode = response.status;
        if (statusCode >= 0 && statusCode <= 999) {
            throw new ErrorsException(await response.json() as Errors);
        }

        throw new UnknownStatusCodeException('The server returned an unknown status code: ' + statusCode);
    }



}
