/**
 * SearchTag automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import axios, {AxiosRequestConfig} from "axios";
import {TagAbstract} from "sdkgen-client"
import {ClientException, UnknownStatusCodeException} from "sdkgen-client";

import {Fields} from "./Fields";
import {Pagination} from "./Pagination";
import {TweetCollection} from "./TweetCollection";

export class SearchTag extends TagAbstract {
    /**
     * @returns {Promise<TweetCollection>}
     * @throws {ClientException}
     */
    public async getRecent(query?: string, sortOrder?: string, expansions?: string, pagination?: Pagination, fields?: Fields): Promise<TweetCollection> {
        const url = this.parser.url('/2/tweets/search/recent', {
        });

        let params: AxiosRequestConfig = {
            url: url,
            method: 'GET',
            headers: {
            },
            params: this.parser.query({
                'query': query,
                'sort_order': sortOrder,
                'expansions': expansions,
                'pagination': pagination,
                'fields': fields,
            }, [
                'pagination',
                'fields',
            ]),
        };

        try {
            const response = await this.httpClient.request<TweetCollection>(params);
            return response.data;
        } catch (error) {
            if (error instanceof ClientException) {
                throw error;
            } else if (axios.isAxiosError(error) && error.response) {
                const statusCode = error.response.status;

                throw new UnknownStatusCodeException('The server returned an unknown status code: ' + statusCode);
            } else {
                throw new ClientException('An unknown error occurred: ' + String(error));
            }
        }
    }


}
