/**
 * SearchTag automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import axios, {AxiosRequestConfig} from "axios";
import {TagAbstract} from "sdkgen-client"
import {ClientException, UnknownStatusCodeException} from "sdkgen-client";

import {Fields} from "./Fields";
import {TweetCollection} from "./TweetCollection";

export class SearchTag extends TagAbstract {
    /**
     * @returns {Promise<TweetCollection>}
     * @throws {ClientException}
     */
    public async getRecent(query?: string, startTime?: string, endTime?: string, sinceId?: string, untilId?: string, sortOrder?: string, expansions?: string, maxResults?: number, fields?: Fields): Promise<TweetCollection> {
        const url = this.parser.url('/2/tweets/search/recent', {
        });

        let params: AxiosRequestConfig = {
            url: url,
            method: 'GET',
            params: this.parser.query({
                'query': query,
                'start_time': startTime,
                'end_time': endTime,
                'since_id': sinceId,
                'until_id': untilId,
                'sort_order': sortOrder,
                'expansions': expansions,
                'max_results': maxResults,
                'fields': fields,
            }, [
                'fields',
            ]),
        };

        try {
            const response = await this.httpClient.request<TweetCollection>(params);
            return response.data;
        } catch (error) {
            if (error instanceof ClientException) {
                throw error;
            } else if (axios.isAxiosError(error) && error.response) {
                switch (error.response.status) {
                    default:
                        throw new UnknownStatusCodeException('The server returned an unknown status code');
                }
            } else {
                throw new ClientException('An unknown error occurred: ' + String(error));
            }
        }
    }


}
