/**
 * TrendCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {Trend} from "./Trend";

export interface TrendCollection {
    data?: Array<Trend>
}

