/**
 * TweetCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {TweetDetails} from "./TweetDetails";

export interface TweetCollection {
    data?: Array<TweetDetails>
}

