"""
tweet_create_response automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from dataclasses import dataclass
from dataclasses_json import dataclass_json
from tweet_create_response_message import TweetCreateResponseMessage
@dataclass_json
@dataclass
class TweetCreateResponse:
    data: TweetCreateResponseMessage
