"""
tweet_details automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from dataclasses import dataclass
from dataclasses_json import dataclass_json
from typing import List
@dataclass_json
@dataclass
class TweetDetails:
    id: str
    text: str
    created_at: datetime.datetime
    author_id: str
    edit_history_tweet_ids: List[str]
    conversation_id: str
    in_reply_to_user_id: str
