/**
 * TweetMedia automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface TweetMedia {
    media_ids?: Array<string>
    tagged_user_ids?: Array<string>
}

