"""
tweet_poll automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from dataclasses import dataclass
from dataclasses_json import dataclass_json
from typing import List
@dataclass_json
@dataclass
class TweetPoll:
    duration_minutes: int
    options: List[str]
