/**
 * TweetUsageResponse automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {TweetUsage} from "./TweetUsage";
export interface TweetUsageResponse {
    data?: TweetUsage
}
