/**
 * Tweet automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {TweetGeo} from "./TweetGeo";
import {TweetMedia} from "./TweetMedia";
import {TweetPoll} from "./TweetPoll";
import {TweetReply} from "./TweetReply";
export interface Tweet {
    direct_message_deep_link?: string
    for_super_followers_only?: boolean
    geo?: TweetGeo
    media?: TweetMedia
    poll?: TweetPoll
    quote_tweet_id?: string
    reply?: TweetReply
    reply_settings?: string
    text?: string
}
