"""
tweet_create_response_message automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from dataclasses import dataclass
from dataclasses_json import dataclass_json
@dataclass_json
@dataclass
class TweetCreateResponseMessage:
    id: str
    text: str
