"""
tweet_reply automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from dataclasses import dataclass
from dataclasses_json import dataclass_json
from typing import List
@dataclass_json
@dataclass
class TweetReply:
    exclude_reply_user_ids: List[str]
    in_reply_to_tweet_id: str
