/**
 * TweetDetails automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface TweetDetails {
    id?: string
    text?: string
    created_at?: string
    author_id?: string
    edit_history_tweet_ids?: Array<string>
    conversation_id?: string
    in_reply_to_user_id?: string
}

