"""
tweet_media automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from dataclasses import dataclass
from dataclasses_json import dataclass_json
from typing import List
@dataclass_json
@dataclass
class TweetMedia:
    media_ids: List[str]
    tagged_user_ids: List[str]
