/**
 * TweetCreateResponse automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {TweetCreate} from "./TweetCreate";
export interface TweetCreateResponse {
    data?: TweetCreate
}
