/**
 * TweetDeleteResponse automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {TweetDeleteResponseMessage} from "./TweetDeleteResponseMessage";
export interface TweetDeleteResponse {
    data?: TweetDeleteResponseMessage
}
