/**
 * TweetCreateResponse automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {TweetCreateResponseMessage} from "./TweetCreateResponseMessage";
export interface TweetCreateResponse {
    data?: TweetCreateResponseMessage
}
