"""
tweet_delete_response automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from dataclasses import dataclass
from dataclasses_json import dataclass_json
from tweet_delete_response_message import TweetDeleteResponseMessage
@dataclass_json
@dataclass
class TweetDeleteResponse:
    data: TweetDeleteResponseMessage
