/**
 * TweetDetails automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface TweetDetails {
    author_id?: string
    conversation_id?: string
    created_at?: string
    edit_history_tweet_ids?: Array<string>
    id?: string
    in_reply_to_user_id?: string
    text?: string
}
