"""
tweet_collection_response automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from dataclasses import dataclass
from dataclasses_json import dataclass_json
from typing import List
from tweet_details import TweetDetails
@dataclass_json
@dataclass
class TweetCollectionResponse:
    data: List[TweetDetails]
