"""
tweet automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from dataclasses import dataclass
from dataclasses_json import dataclass_json
from tweet_geo import TweetGeo
from tweet_media import TweetMedia
from tweet_poll import TweetPoll
from tweet_reply import TweetReply
@dataclass_json
@dataclass
class Tweet:
    direct_message_deep_link: str
    for_super_followers_only: bool
    geo: TweetGeo
    media: TweetMedia
    poll: TweetPoll
    quote_tweet_id: str
    reply: TweetReply
    reply_settings: str
    text: str
