/**
 * TweetUsage automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface TweetUsage {
    cap_reset_day?: number
    project_cap?: string
    project_id?: string
    project_usage?: string
}

