/**
 * TweetDeleteResponse automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {TweetDelete} from "./TweetDelete";

export interface TweetDeleteResponse {
    data?: TweetDelete
}

