/**
 * TweetPoll automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface TweetPoll {
    duration_minutes?: number
    options?: Array<string>
}

