/**
 * TweetReply automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface TweetReply {
    exclude_reply_user_ids?: Array<string>
    in_reply_to_tweet_id?: string
}
