/**
 * User automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface User {
    created_at?: string
    id?: string
    name?: string
    pinned_tweet_id?: string
    username?: string
}

