name: SDKgen
on:
  workflow_dispatch:
    inputs:
      typehub_message:
        required: false
      typehub_version:
        required: false
      typehub_changelog:
        required: false
permissions:
  contents: 'write'
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: apioo/sdkgen-generator-action@v0.2.1
        with:
          client_id: '${{ secrets.SDKGEN_CLIENT_ID }}'
          client_secret: '${{ secrets.SDKGEN_CLIENT_SECRET }}'
          typehub_message: '${{ inputs.typehub_message }}'
          typehub_version: '${{ inputs.typehub_version }}'
          typehub_changelog: '${{ inputs.typehub_changelog }}'
  publish:
    needs: generate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm version ${{ inputs.typehub_version }} --no-git-tag-version
      - run: npm ci
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
